version: '3.7'

services:
  ghost:
    image: ghost:latest
    container_name: ghost-theme-docker
    volumes:
      - ./okctl-io-ghost-tema:/var/lib/ghost/content/themes/okctl
    ports:
      - "80:2368"
    environment:
        database__client: mysql
        database__connection__host: ghost_mysql
        database__connection__user: root
        database__connection__password: <replace-me>
        database__connection__database: ghost
        url: http://localtest.me
        NODE_ENV: development

  ghost_mysql:
    image: mariadb
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: <replace-me>
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql:
