name: Build & Deploy Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  # Build CSS files from .scss
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp build

      # Inject the search API key into the output
      - name: Inject Environment Variables
        uses: pedrolamas/handlebars-action@v1.0.4
        with:
          files: 'partials/api-key.hbs'
          output-filename: 'partials/api-key.hbs'
          html-escape: true
          dry-run: true

      # Deploy the theme to Ghost using the Admin API key
      - uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}